doctrine_migrations:
    migrations_paths:
        # namespace should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'Trailmind\Migrations': '%kernel.project_dir%/src/Migrations'
    enable_profiler: false
