version: '3.9'

services:
  db:
    image: postgis/postgis:18-3.6
    container_name: trailmind-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: trailmind
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: trailmind
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trailmind"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: trailmind-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
