default:
  formatters:
    pretty: false
    progress: true

  suites:
    default:
      paths:
        features: features/scenarios
      contexts:
        - TestingInfrastructure\Context\Feature\FeatureContext
        - TestingInfrastructure\Context\Trail\TrailContext
        - TestingInfrastructure\Context\Register\RegisterContext
        - TestingInfrastructure\Context\Request\RequestContext
        - TestingInfrastructure\Context\Response\ResponseContext
        - TestingInfrastructure\Context\User\UserContext

  gherkin:
    filters:
      tags: ~@wip

  extensions:
    FriendsOfBehat\SymfonyExtension:
      bootstrap: features/bootstrap/bootstrap.php
      kernel:
        class: App\Kernel
        environment: test
        debug: true

    Behat\MinkExtension:
      base_url: 'http://api.develop.trailmind.co.uk/'
      sessions:
        default:
          symfony: ~